import {
  Home,
  Building,
  Gem,
  Hotel,
  Building2,
  Store,
  Users,
  CalendarDays,
  UtensilsCrossed,
  ExternalLink,
  Wind,
  Factory,
  Bug,
  Droplets,
  MousePointer2,
  Sparkles,
  Wrench,
  UserCheck,
  HardHat,
} from "lucide-react";

export interface Service {
  id: string;
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  description: string;
  bullets: string[];
  image: string;
  color: string;
  bgColor: string;
  textColor: string;
}

export const ALL_SERVICES: Service[] = [
  {
    id: "nettoyage-villa",
    icon: Home,
    title: "Nettoyage Villa",
    description: "Nettoyage complet et professionnel de villas et maisons individuelles. Un intérieur impeccable pour votre confort quotidien.",
    bullets: ["Nettoyage complet des pièces", "Traitement des sols et surfaces", "Désinfection sanitaires"],
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop",
    color: "from-blue-500 to-cyan-500",
    bgColor: "bg-blue-500/10",
    textColor: "text-blue-600",
  },
  {
    id: "nettoyage-copropriete",
    icon: Building,
    title: "Nettoyage Copropriété",
    description: "Entretien régulier des parties communes d'immeubles et résidences. Halls, escaliers, ascenseurs impeccables.",
    bullets: ["Parties communes", "Halls et escaliers", "Espaces verts"],
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    color: "from-indigo-500 to-purple-500",
    bgColor: "bg-indigo-500/10",
    textColor: "text-indigo-600",
  },
  {
    id: "cristallisation-marbre-parquet",
    icon: Gem,
    title: "Cristallisation Marbre & Parquet",
    description: "Cristallisation et rénovation pour redonner éclat à vos sols nobles. Expertise en marbre, granit et parquet.",
    bullets: ["Cristallisation marbre", "Vitrification parquet", "Polissage professionnel"],
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop",
    color: "from-pink-500 to-rose-500",
    bgColor: "bg-pink-500/10",
    textColor: "text-pink-600",
  },
  {
    id: "nettoyage-hotel",
    icon: Hotel,
    title: "Nettoyage Hôtel",
    description: "Standards d'hygiène premium pour l'hôtellerie. Chambres, parties communes et espaces de réception.",
    bullets: ["Chambres & suites", "Parties communes", "Espaces de réception"],
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop",
    color: "from-amber-500 to-orange-500",
    bgColor: "bg-amber-500/10",
    textColor: "text-amber-600",
  },
  {
    id: "nettoyage-appartement",
    icon: Building2,
    title: "Nettoyage Appartement",
    description: "Nettoyage en profondeur pour appartements. Service ponctuel ou régulier selon vos besoins.",
    bullets: ["Nettoyage complet", "Service régulier disponible", "Produits écologiques"],
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    color: "from-teal-500 to-cyan-500",
    bgColor: "bg-teal-500/10",
    textColor: "text-teal-600",
  },
  {
    id: "nettoyage-locaux-commerciaux",
    icon: Store,
    title: "Nettoyage Locaux Commerciaux",
    description: "Entretien professionnel pour boutiques, showrooms et espaces commerciaux. Image impeccable garantie.",
    bullets: ["Boutiques & showrooms", "Vitrines", "Sols et surfaces"],
    image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=600&h=400&fit=crop",
    color: "from-violet-500 to-purple-500",
    bgColor: "bg-violet-500/10",
    textColor: "text-violet-600",
  },
  {
    id: "nettoyage-residence-immeuble",
    icon: Building,
    title: "Nettoyage Résidence & Immeuble",
    description: "Gestion complète de l'entretien des résidences et immeubles. Contrats sur mesure pour syndics.",
    bullets: ["Parties communes", "Gestion déchets", "Entretien espaces verts"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    color: "from-slate-500 to-gray-600",
    bgColor: "bg-slate-500/10",
    textColor: "text-slate-600",
  },
  {
    id: "nettoyage-evenementiel",
    icon: CalendarDays,
    title: "Nettoyage Événementiel",
    description: "Nettoyage avant, pendant et après vos événements professionnels. Service rapide et discret.",
    bullets: ["Préparation des espaces", "Entretien pendant l'événement", "Remise en état après"],
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600&h=400&fit=crop",
    color: "from-fuchsia-500 to-pink-500",
    bgColor: "bg-fuchsia-500/10",
    textColor: "text-fuchsia-600",
  },
  {
    id: "nettoyage-restaurant",
    icon: UtensilsCrossed,
    title: "Nettoyage Restaurant",
    description: "Hygiène irréprochable pour restaurants et cuisines professionnelles. Conformité aux normes HACCP.",
    bullets: ["Cuisines professionnelles", "Salles de restaurant", "Normes HACCP"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
    color: "from-red-500 to-orange-500",
    bgColor: "bg-red-500/10",
    textColor: "text-red-600",
  },
  {
    id: "nettoyage-facade",
    icon: ExternalLink,
    title: "Nettoyage Façade",
    description: "Nettoyage extérieur de façades, vitrages et enseignes. Redonnez de l'éclat à votre bâtiment.",
    bullets: ["Façades & murs extérieurs", "Vitrages en hauteur", "Enseignes lumineuses"],
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&h=400&fit=crop",
    color: "from-sky-500 to-blue-500",
    bgColor: "bg-sky-500/10",
    textColor: "text-sky-600",
  },
  {
    id: "nettoyage-sec",
    icon: Wind,
    title: "Nettoyage Sec",
    description: "Nettoyage à sec professionnel pour tapis, moquettes, canapés et textiles délicats.",
    bullets: ["Tapis & moquettes", "Canapés & fauteuils", "Textiles délicats"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    color: "from-cyan-500 to-teal-500",
    bgColor: "bg-cyan-500/10",
    textColor: "text-cyan-600",
  },
  {
    id: "nettoyage-industriel",
    icon: Factory,
    title: "Nettoyage Industriel",
    description: "Solutions spécialisées pour usines, entrepôts et sites de production. Équipement professionnel.",
    bullets: ["Grandes surfaces industrielles", "Équipement professionnel", "Normes de sécurité respectées"],
    image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=600&h=400&fit=crop",
    color: "from-gray-500 to-slate-600",
    bgColor: "bg-gray-500/10",
    textColor: "text-gray-600",
  },
  {
    id: "desinsectisation",
    icon: Bug,
    title: "Désinsectisation",
    description: "Élimination professionnelle des insectes nuisibles : cafards, punaises, fourmis, moustiques.",
    bullets: ["Cafards & blattes", "Punaises de lit", "Fourmis & moustiques"],
    image: "https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=600&h=400&fit=crop",
    color: "from-lime-500 to-green-500",
    bgColor: "bg-lime-500/10",
    textColor: "text-lime-600",
  },
  {
    id: "assainissement",
    icon: Droplets,
    title: "Assainissement",
    description: "Services d'assainissement et traitement des eaux usées. Débouchage et curage de canalisations.",
    bullets: ["Débouchage canalisations", "Curage fosses septiques", "Traitement eaux usées"],
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=400&fit=crop",
    color: "from-blue-600 to-indigo-600",
    bgColor: "bg-blue-600/10",
    textColor: "text-blue-700",
  },
  {
    id: "deratisation",
    icon: MousePointer2,
    title: "Dératisation",
    description: "Lutte efficace contre les rongeurs : rats, souris. Traitement préventif et curatif.",
    bullets: ["Rats & souris", "Traitement préventif", "Solutions durables"],
    image: "https://images.unsplash.com/photo-1615824996195-f780bba7cfab?w=600&h=400&fit=crop",
    color: "from-orange-500 to-red-500",
    bgColor: "bg-orange-500/10",
    textColor: "text-orange-600",
  },
  {
    id: "hygiene",
    icon: Sparkles,
    title: "Hygiène",
    description: "Solutions complètes d'hygiène professionnelle. Distributeurs, consommables et maintenance.",
    bullets: ["Distributeurs savon/papier", "Consommables hygiéniques", "Maintenance régulière"],
    image: "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=600&h=400&fit=crop",
    color: "from-emerald-500 to-teal-500",
    bgColor: "bg-emerald-500/10",
    textColor: "text-emerald-600",
  },
  {
    id: "entretien-renovation",
    icon: Wrench,
    title: "Entretien et Rénovation",
    description: "Services d'entretien et petits travaux de rénovation. Maintenance préventive de vos locaux.",
    bullets: ["Petits travaux", "Maintenance préventive", "Réparations diverses"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=400&fit=crop",
    color: "from-yellow-500 to-amber-500",
    bgColor: "bg-yellow-500/10",
    textColor: "text-yellow-600",
  },
  {
    id: "personnel-qualifie",
    icon: UserCheck,
    title: "Personnel Qualifié",
    description: "Mise à disposition de personnel formé : agents d'entretien, femmes de ménage, agents de sécurité.",
    bullets: ["Personnel formé", "Service discret & rigoureux", "Flexibilité totale"],
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&h=400&fit=crop",
    color: "from-indigo-500 to-blue-500",
    bgColor: "bg-indigo-500/10",
    textColor: "text-indigo-600",
  },
  {
    id: "nettoyage-post-chantier",
    icon: HardHat,
    title: "Nettoyage Post-Chantier",
    description: "Remise en état complète après travaux de construction ou rénovation. Prêt à habiter.",
    bullets: ["Poussières & résidus", "Vitres & menuiseries", "Prêt à habiter"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    color: "from-green-500 to-emerald-500",
    bgColor: "bg-green-500/10",
    textColor: "text-green-600",
  },
];

// Featured services for homepage carousel (first 6)
export const FEATURED_SERVICES = ALL_SERVICES.slice(0, 9);
